name: Build and Deploy

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:

    - name: Deploy to Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ vars.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          docker pull ${{ vars.DOCKER_REGISTRY }}/${{ vars.DOCKER_IMAGE }}:$IMAGE_TAG
          docker stop ${{ vars.DOCKER_IMAGE }} || true
          docker rm ${{ vars.DOCKER_IMAGE }} || true
          docker run -d --name ${{ vars.DOCKER_IMAGE }} -p 3005:8080 ${{ vars.DOCKER_REGISTRY }}/${{ vars.DOCKER_IMAGE }}:$IMAGE_TAG